### ISSUE TITLE
pls fix the dog jaw green stripe

### ISSUE THREAD

**Issue by iamweirdie** [vadis365/Animalium#1]
![](https://i.imgur.com/Oe0Kf4Y.png)

also sorry for posting on curseforge too, i wanted to be sure. i'm not gonna clone this message i swear

**Comment by vadis365** [comment]
it's not broken though.

**Comment by iamweirdie** [comment]
Right but it's a texture mishap

**Comment by vadis365** [comment]
cool, I'll add a green stripe to the other side too, to even it up :+1:

**Comment by iamweirdie** [comment]
thank u
