### ISSUE TITLE
(question) fabric or forge?

### ISSUE THREAD

**Issue by systox** [vadis365/Animalium#12]
Ambiguous file in downloads section. Cannot tell if for forge or is also compatible with fabric on 1.16.1 

Thank you

**Comment by vadis365** [comment]
Not sure where you are getting the file from, but if it isn't curseforge then it is an illegal re-hosted mod.
If on the otherhand you are downloading from curseforge it does actually state what version and compat.
![clear](https://user-images.githubusercontent.com/6518708/87211796-1574ea00-c313-11ea-9fa5-cfc5efc34209.png)
