### ISSUE TITLE
Server crash while starting up.

### ISSUE THREAD

**Issue by Darkfiend009** [vadis365/Animalium#3]
Server crashes while attempting to launch.

Mod Version: Animalium 0.5.1
Forge Version: 30.0.30
Minecraft Version: 1.15.1

Crash Report: 
https://pastebin.com/EpcJ7YYv

**Comment by ghost** [comment]
I have the same problem.

**Comment by KnifeOfDunwall** [comment]
me too. only on 1.14.4

**Comment by vadis365** [comment]
I think I have fixed this in a later version now and will backport if it is confirmed OK.
see #8 as it is an identical report.

**Comment by vadis365** [comment]
Closing because it is fixed in the last 2 game versions.
