### ISSUE TITLE
(Question) wild dog boots in 1.14

### ISSUE THREAD

**Issue by KnifeOfDunwall** [vadis365/Animalium#6]
the wild dog boots in 1.12 broke really fast. but in 1.14 they break in one hit. is this intended behaviour or can i toggle it off?

**Comment by vadis365** [comment]
aw crap, yeah just seen it in the code - my bad
will push another update in a day or so to fix this - just pushed a 1.15.2 update with the same issue but it's too late to change it atm.
I should check the issues more often - bad mod dev!

**Comment by vadis365** [comment]
Not sure if this issue is still a thing as the mod has updated to more recent versions of the game and 1.14. seems like it isn't going to be used.
