### ISSUE TITLE
[1.15.2] Ticking Entity on Client Crash

### ISSUE THREAD

**Issue by mr-poyo** [vadis365/Animalium#9]
**Forge:** 31.1.77
**Version:** Animalium-0.5.3.jar

I'm testing my SMP custom modpack on 1.15.2 and I encountered a weird crash that crashed my Client only. Server was unscathed. All I did was afk for a bit, came back for testing scoreboards and did /kill (part of my scoreboard test). After dying, I got this crash.

https://pastebin.com/GsZRWD4d

I've had a similar crash with the rat from Animalium (that killed me in survival mode) a couple of days ago.

Older, but same type of crash with the rat entity: https://pastebin.com/pHtiEKMS

**EDIT:** I nuked my configs on client/server because I made some edits. So far so good. Perhaps I put a bad value in there somewhere. Will test some more..

EDIT2: Perhaps that was it.. What's the proper value if I want a 0% chance for piranha's hurting boats / rats stealing items? I put 0 before.

**Comment by vadis365** [comment]
PIRANHA_DAMAGE_BOATS = false
RAT_STEALS_ITEMS = false
should be the 2 things to change there and it'll ignore the chance (the chance isn't a percentage it is a random chance of 1:X so the higher the number the less chance)
